version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: order_system
      MYSQL_USER: order
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_system
      SPRING_DATASOURCE_USERNAME: order
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
      - redis