version: '3.8'
services:
#  mysql:
#    image: mysql:8.0
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: order_system
#      MYSQL_USER: order
#      MYSQL_PASSWORD: 1234
#      MYSQL_ROOT_PASSWORD: 1234

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://order-database.cufq4kyocjf6.ap-northeast-2.rds.amazonaws.com:3306/order_system
      SPRING_DATASOURCE_USERNAME: minu
      SPRING_DATASOURCE_PASSWORD: ordersystem
    depends_on:
#      - mysql
      - redis