spring:
  profiles:
    active: dev  # application.yml 공통 부분 동작 후 application-dav.yml 동작

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

oauth:
#  google:
#    secret: ${google.client-secret}
#    client-id: ${google.client-id}
#    url:
#      auth: https://accounts.google.com
#      api: https://googleapis.com
  kakao:
    client-id: ${kakao.client-id}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ${naver.client-secret}
    client-id: ${naver.client-id}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

cloud:
  aws:
    region:
      static: ${aws.region}
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    s3:
      bucket: ${aws.bucket}

jwt:
  secret: ${jwt.secret-key}

springdoc:
  packages-to-scan : jpabook.jpashop
  swagger-ui :
    path : /api
  api-docs :
    path : /api-docs/json
    groups :
      enabled : true
  cache :
    disabled : true
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8