spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://order-database.cufq4kyocjf6.ap-northeast-2.rds.amazonaws.com:3306/order_system
    username: minu
    password: ordersystem

  sql:
    init:
      mode: always  # 모든 데이터베이스의 sql script 를 동작시키는 'always', embedded(내장) 데이터베이스만 동작시키는 'embedded', 모든 데이터베이스를 동작시키지 않는 'never'

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true  # jpa.hibernate.ddl-auto 실행 후 sql script 실행

logging:
  level:
    root: INFO