spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_system  # 도커 컨테이너 이름 mysql
    username: order
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: false  # 엔티티와 flyway 에서 생성하는 테이블이 같아 aal-auto: create-drop 으로 인해 데이터 삽입 불가능

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql  # *.sql 경로

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true  # Hibernate 의 초기 엔티티 생성 이후 *.sql 실행

logging:
  level:
    root: INFO